// Generated by CoffeeScript 1.9.3
(function() {
  var activity, bol, i, len, manager, numbers, relax, site;

  bol = true;

  if (bol) {
    console.log("Bismillah Alrehman Alrahim");
  }

  numbers = [1, 2, 3, 4];

  if (bol) {
    runForLife();
  }

  if (bol) {
    runForLife();
  }

  while (bol) {
    scream();
  }

  activity = sunday && monday || tuesday && !thursday ? chill() : relax();

  while (bol) {
    relax;
  }

  while (bol) {
    relax;
  }

  while (!monday) {
    chill;
  }

  for (i = 0, len = sites.length; i < len; i++) {
    site = sites[i];
    chill;
  }

  for (site in sites) {
    manager = sites[site];
    relax;
  }

  relax = function(a, b) {
    if (b == null) {
      b = "true";
    }
    return console.log(a + b);
  };

}).call(this);

//# sourceMappingURL=cScript.js.map
